AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - cobra_commander.gemspec

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
