sudo: true
language: ruby
rvm:
  - 2.3.1
before_install:
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - gem install bundler:1.13.6
  - sudo apt-get -qq install graphviz
