sudo: true
language: ruby
rvm:
  - 2.3.1
before_install:
  - gem install bundler:1.13.6
  - sudo apt-get -qq install graphviz
install:
  - bundle _1.13.6_ install --jobs=3 --retry=3
script:
  - bundle _1.13.6_ exec rake
