name: CI

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.5"
          - "2.6"
          - "2.7"
        bundler:
          - "1"
          - "2"
    env:
      BUNDLE_GEMFILE: gemfiles/bundler${{ matrix.bundler }}.gemfile
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: ${{ matrix.bundler }}
        bundler-cache: true
    - name: Install alternative versions of bundler
      run: gem install bundler -v ~> 1 --no-document; gem install bundler -v ~> 2 --no-document
    - name: Install Graphviz
      run: sudo apt -qq install graphviz
    - name: Run tests
      run: bundle exec rake spec
  lint:
    name: Lint Ruby
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rubocop
      uses: reviewdog/action-rubocop@v1
      with:
        rubocop_version: 0.88.0
        filter_mode: nofilter
        fail_on_error: true
        rubocop_extensions: ""
        github_token: ${{ secrets.github_token }}
