name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Lint Ruby
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "2.5"
          - "2.6"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 1
        bundler-cache: true
    - name: rubocop
      uses: reviewdog/action-rubocop@v1
      with:
        rubocop_version: 0.48.1
        github_token: ${{ secrets.github_token }}
